### ISSUE TITLE
Problem with v11.5.30 - can't open via contextmenu

### ISSUE THREAD

**Issue by mtness** [liayn/t3ext-wizard_crpagetree#11]
The wizard cant be opened via contextmenu anymore - 
there seems to be an error in the Contextmenuactions:
"Uncaught Error: Script error for "TYPO3/CMS/WizardCrpagetree/ContextMenuActions"
https://requirejs.org/docs/errors.html#scripterror"

However, when I copy the link via inspector the page can be opened in a new tab.

**Comment by mtness** [comment]
Update:
The curent version produces a warning when trying to open page via contextmenu:

`Core: Exception handler (WEB):  Uncaught TYPO3 Exception: #1476107295: PHP Warning: Trying to access  array offset on value of type null in  /var/www/html/vendor/reelworx/wizard-crpagetree/Classes/NewPagetreeController.php  line 118`

**Comment by liayn** [comment]
Resolved
