### ISSUE TITLE
Not installable via composer in 9.5.x

### ISSUE THREAD

**Issue by georgringer** [liayn/t3ext-wizard_crpagetree#3]
Currently the requirement is `"typo3/cms": "^7.6 || ^8.7 || ^9.5"`

Since 8 it is possible and this is the best practice way to only install those sysexts which are needed. Therefore the requirement must be changed for 8 & 9 to `typo3/cms-core`.

I propose using a custom branch for 7 support and release new versions for 8+9, there are also couple of other things which could be improved then. feel free to contact me via slack if you need help

**Comment by liayn** [comment]
Branch master is now for v8+ and branch 7-6 is legacy.
Will release a v2.1.1 in TER for T3 7 and will release a v3.0.0 for T3 8.

Please create a PR with all your suggests for master, so that we have a bit more in the v3 release. Thanks.

**Comment by liayn** [comment]
I think this is history and can be closed.
