### ISSUE TITLE
Fluid UnknownNamespaceException in v10

### ISSUE THREAD

**Issue by gaumondp** [liayn/t3ext-wizard_crpagetree#6]
TYPO3 10.4.16 Composer, DDEV and Introduction package

After a right-click to use the Wizard we got:

TYPO3Fluid\Fluid\Core\Parser\UnknownNamespaceException
Fluid parse error in template Standard_action_index_c66a29a728b959a5867d5e032d91dc10458745b0, line 55 at character 9. Error: Unknown Namespace: be (error code 0). Template source chunk: <form action="{be:moduleLink(route:'pagetree_new', arguments:'{id:pageUid}')}" method="post"> <div class="form-group t3js-newpagetree-container"> <div class="form-section"> <div class="row"> <div class="form-group col-xs-12"> <label for="page_new_0">

Even after clearing all caches.

**Comment by liayn** [comment]
I tried with current 10.4.17 and I do not have such an issue. I can't reproduce.

**Comment by liayn** [comment]
Oh, I tested current master, which fixed this issue already. Will create a new release

**Comment by liayn** [comment]
See: https://extensions.typo3.org/extension/wizard_crpagetree

**Comment by gaumondp** [comment]
I confirm 4.0.2 fixed the problem.

Many thanks. We use the extension quite often in our 7k pages website. It's a lifesaver!
